//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingPlane.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VIPProjectEntities : DbContext
    {
        public VIPProjectEntities()
            : base("name=VIPProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<db_Booking> db_Booking { get; set; }
        public virtual DbSet<db_Checkin> db_Checkin { get; set; }
        public virtual DbSet<db_ChoNgoi> db_ChoNgoi { get; set; }
        public virtual DbSet<db_ChuongTrinhKhuyenMai> db_ChuongTrinhKhuyenMai { get; set; }
        public virtual DbSet<db_ChuyenBay> db_ChuyenBay { get; set; }
        public virtual DbSet<db_DieuKhoan> db_DieuKhoan { get; set; }
        public virtual DbSet<db_HanhKhach> db_HanhKhach { get; set; }
        public virtual DbSet<db_PTTT> db_PTTT { get; set; }
        public virtual DbSet<db_SanBay> db_SanBay { get; set; }
        public virtual DbSet<db_User> db_User { get; set; }
        public virtual DbSet<db_Ve> db_Ve { get; set; }
    }
}
