//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingPlane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_Booking()
        {
            this.db_Checkin = new HashSet<db_Checkin>();
            this.db_HanhKhach = new HashSet<db_HanhKhach>();
            this.db_PTTT = new HashSet<db_PTTT>();
        }
    
        public int IDBK { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> IDCB { get; set; }
        public Nullable<int> IDV { get; set; }
        public System.DateTime NgayDat { get; set; }
        public string TrangThai { get; set; }
        public double TongGia { get; set; }
        public int SoHanhKhack { get; set; }
        public Nullable<int> KhuyenMai { get; set; }
    
        public virtual db_ChuyenBay db_ChuyenBay { get; set; }
        public virtual db_User db_User { get; set; }
        public virtual db_Ve db_Ve { get; set; }
        public virtual db_ChuongTrinhKhuyenMai db_ChuongTrinhKhuyenMai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Checkin> db_Checkin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_HanhKhach> db_HanhKhach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_PTTT> db_PTTT { get; set; }
    }
}
