//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingPlane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Checkin
    {
        public int IDCKin { get; set; }
        public Nullable<int> IDBK { get; set; }
        public Nullable<int> IDHK { get; set; }
        public Nullable<System.DateTime> GioCI { get; set; }
        public string SoGhe { get; set; }
        public string TrangThai { get; set; }
    
        public virtual db_Booking db_Booking { get; set; }
        public virtual db_HanhKhach db_HanhKhach { get; set; }
    }
}
