//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingPlane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_ChoNgoi
    {
        public int IDCN { get; set; }
        public Nullable<int> IDCB { get; set; }
        public string SoGhe { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> IDHK { get; set; }
    
        public virtual db_ChuyenBay db_ChuyenBay { get; set; }
    }
}
