//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingPlane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_ChuyenBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_ChuyenBay()
        {
            this.db_Booking = new HashSet<db_Booking>();
            this.db_ChoNgoi = new HashSet<db_ChoNgoi>();
            this.db_ChuongTrinhKhuyenMai = new HashSet<db_ChuongTrinhKhuyenMai>();
            this.db_Ve = new HashSet<db_Ve>();
        }
    
        public int IDCB { get; set; }
        public string SoHieu { get; set; }
        public string SanBayDi { get; set; }
        public string SanBayDen { get; set; }
        public System.DateTime NgayGioKhoiHanh { get; set; }
        public System.DateTime NgayGioDen { get; set; }
        public int SoVeConLai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Booking> db_Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_ChoNgoi> db_ChoNgoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_ChuongTrinhKhuyenMai> db_ChuongTrinhKhuyenMai { get; set; }
        public virtual db_SanBay db_SanBay { get; set; }
        public virtual db_SanBay db_SanBay1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Ve> db_Ve { get; set; }
    }
}
