//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingPlane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_PTTT
    {
        public string IDPT { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> IDBK { get; set; }
        public string TenPT { get; set; }
        public string ChiTiet { get; set; }
    
        public virtual db_Booking db_Booking { get; set; }
        public virtual db_User db_User { get; set; }
    }
}
