//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingPlane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_SanBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_SanBay()
        {
            this.db_ChuyenBay = new HashSet<db_ChuyenBay>();
            this.db_ChuyenBay1 = new HashSet<db_ChuyenBay>();
        }
    
        public string IDSB { get; set; }
        public string TenSB { get; set; }
        public string ThanhPho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_ChuyenBay> db_ChuyenBay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_ChuyenBay> db_ChuyenBay1 { get; set; }
    }
}
