//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingPlane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_User()
        {
            this.db_Booking = new HashSet<db_Booking>();
            this.db_ChuongTrinhKhuyenMai = new HashSet<db_ChuongTrinhKhuyenMai>();
            this.db_PTTT = new HashSet<db_PTTT>();
        }
    
        public int IDUser { get; set; }
        public string TenUser { get; set; }
        public string Password { get; set; }
        public string RoleUser { get; set; }
        public string Email { get; set; }
        public Nullable<int> DiemTichLuy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Booking> db_Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_ChuongTrinhKhuyenMai> db_ChuongTrinhKhuyenMai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_PTTT> db_PTTT { get; set; }
    }
}
